name: TheBridge
main: com.leo.thebridge.Main
author: Leonardo
version: 1.0BETA
dependencies: [VirtualWorldsAPI]
commands:
  entrar:
    description: Join to a game.
  forcestart:
    description: Force start the game.
    permission: thebridge.admin
  forcestop:
    description: Force stop the game.
    permission: thebridge.admin
